server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
  servlet:
    jsp:
      init-parameters:
        development: true


spring:
  datasource:
    username: c##wei
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.56.1:1521/orcl

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate

  profiles:
    active: dev

  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true

  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 100MB

  jackson:
    default-property-inclusion: non_null

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制） max-active: 2000
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000


mybatis-plus:
  type-aliases-package: cc.mrbird.febs.*.entity
  mapper-locations: classpath:mapper/system/*.xml
  configuration:
    jdbc-type-for-null: null
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: oracle
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
      id-type: input

logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            metadata:
              TableInfoHelper: error

day:
  value: 3